spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: jdbc:postgresql://${PRD_DB_HOST}:5432/orders_prd
    username: ${PRD_DB_USER}
    password: ${PRD_DB_PASSWORD}
  cloud:
    gcp:
      pubsub:
        enabled: true
        project-id: ${PRD_GCP_PROJECT}

orders:
  pubsub:
    enabled: true
    created-topic: orders.created.prd
    status-changed-topic: orders.status-changed.prd
